### ISSUE TITLE
Calling setString with null value throws error

### ISSUE THREAD

**Issue by nicodumdum** [dreamsoftin/obscured_preferences#2]
Hi,

Since this package usage and syntax follows that of [shared_preferences](https://pub.dartlang.org/packages/shared_preferences), I was on that assumption that if I call any value setters with a null value, it will default to something like calling the [remove()](https://pub.dev/documentation/shared_preferences/latest/shared_preferences/SharedPreferences/remove.html) method in [shared_preferences](https://pub.dartlang.org/packages/shared_preferences).

However, when I tried calling `await obscuredPreferences.setString('someKey', null);` it threw a null related error.

I am not sure if it's a bug or an expected behavior, but I was hoping it would behave the same as original shared preferences `await sharedPreferences.setString('someKey', null);` wherein it will just remove the key and not throw an error.

Thanks!

EDIT: Here's the error output btw.
![Screenshot 2020-11-03 150555](https://user-images.githubusercontent.com/1650987/97957717-b9b0fe00-1de6-11eb-9355-22d507b294c7.png)

**Comment by SachinGanesh** [comment]
@nicodumdum Thanks for letting us know. We will fix this issue.
